language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "N97E0/gAPm4Yz3jjEbST2/uuNNUTuralGS51fFnkiNmr407n0oW4pmF59IIGnVMQZ+tkO8IqcrzSR1N2YTWVA7YIN392DnXmeUeRXpLlxtObeZPGjaS3q84VniIfFgYC/eax7rHRzyaBgM2DnvpYi9t45jcBaf63GS3byApD1Go="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
